#!/bin/sh
SERVICE_NAME=wsapp
PATH_TO_JAR=/jmdata/qp/ws
PID_PATH_NAME=/tmp/wsapp-pid
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            cd $PATH_TO_JAR
            nohup java -Dfile.encoding=UTF-8 -jar $PATH_TO_JAR/app.jar /tmp 2>> /dev/null >> /dev/null &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill -9 $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        service $SERVICE_NAME stop
        service $SERVICE_NAME start
    ;;
esac